#端口号
server:
  port: 9002
  tomcat:
    uri-encoding: UTF-8
#数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jxwly56_db?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jxwly56
    password: 4Jz.cprpVcY3w8M
  #热部署
  devtools:
    restart:
      enabled: true  #设置开启热部署
      # additional-paths: classpath:cn/lena/weblog/** #重启目录
      # exclude: classpath:static/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
  #自定义静态文件夹路径
  mvc:
    static-path-pattern: /static/**

#分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#mybatis的配置
mybatis:
  type-aliases-package: com.jingchu.web.domain   #设置别名
  mapper-locations: classpath:mapper/*.xml   #ָ指定mapper映射文件
  configuration:
    mapUnderscoreToCamelCase: true
